- hosts: masters
  become: yes
  tasks:
  
    - name: Install cilium cni
      become: yes
      become_user: root
      shell: |
              curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/v0.12.11/cilium-linux-amd64.tar.gz{,.sha256sum}
              sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin
              rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
      #command: sh 'CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/master/stable.txt)'
      #command: sh 'CLI_ARCH=amd64'
      #command: sh 'if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi'
      #command: sh 'curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/v0.12.11/cilium-linux-amd64.tar.gz{,.sha256sum}'
      #command: sh 'sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin'
      #command: sh 'rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}'


              #CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/master/stable.txt) /
              #CLI_ARCH=amd64 /
              #if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi /
              #curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}  
              #sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin 
              #rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}