#Reference - https://www.ansiblepilot.com/articles/mount-an-nfs-share-in-linux-ansible-module-mount/
- name: mount module demo
  hosts: all
  become: true
  vars:
    mynfs: "nfs01:/data"
    mountpoint: "/nfs-share"
    permission: '0777'
    myopts: 'rw,sync'
  tasks:
    - name: utility present debian-like
      ansible.builtin.apt:
        name:
          - nfs-common
          - nfs4-acl-tools
        state: present
      when: ansible_os_family == 'Debian'

    - name: check mountpoint exist
      ansible.builtin.file:
        path: "{{ mountpoint }}"
        state: directory
        mode: "{{ permission }}"
        owner: nobody
        group: nogroup

    - name: mount network share
      ansible.posix.mount:
        src: "{{ mynfs }}"
        path: "{{ mountpoint }}"
        fstype: nfs
        opts: "{{ myopts }}"
        state: mounted

        